<?php

// regex
const REGEX_MOBILE = "/^09[0-9]{9}$/";

const AUTH_TOKEN_NAME = 'authToken';
const LENGTH_AUTH_CODE = 5;
const AUTH_CODE_EXPIRE_TIME = 90;
const AUTH_CODE_FAKE = true;
const COSTS_DATE_FORMAT = 'Y-m-d';
const COSTS_SYNC_PAGINATE = 500;
const DEVICE_INFO_ENCODE = 'base64';

const LENGTH_LOCATION_INFO_TITLE = 128;
const LENGTH_LOCATION_INFO_DESCRIPTION = 300;
